### ISSUE TITLE
Remote config adapter isn't provided

### ISSUE THREAD

**Issue by liulei008** [Nepxion/Docs#2]
![image](https://user-images.githubusercontent.com/18674070/56861428-3766a300-69d3-11e9-8b4c-df308b268aad.png)

discovery 2019-04-28 16:31:00,011 ERROR [http-nio-2222-exec-7] c.n.d.c.e.ConsoleEndpoint [ConsoleEndpoint.java:368] - Remote config adapter isn't provided

**Comment by HaojunRen** [comment]
需要自行引入那个配置中心？例如Apollo，Nacos等
