### ISSUE TITLE
Zuul Filter 添加header在MyDiscoveryEnabledStrategy里无法获取

### ISSUE THREAD

**Issue by xxy1981** [Nepxion/Docs#3]
你好，我在Zuul网关的Filter里新增一个Header，例如：context.addZuulRequestHeader("reqRegion", "qa");  在网关的DiscoveryEnabledStrategy实现类里缺无法拿到这个header，比如：
HttpServletRequest request = zuulStrategyContextHolder.getRequest();
String reqRegion = request.getHeader("reqRegion");
reqRegion获取到的是空，但postman测试时HTTP设置的头属性是可以正常获取到值的，同时我debug时发现，Zuul Filter通过addZuulRequestHeader设置的值，虽然在Zuul的MyDiscoveryEnabledStrategy里无法获取到，但这个Header信息却能传递到后端服务，服务层的MyDiscoveryEnabledStrategy 的serviceStrategyContextHolder 对象里是可以正常获取到的。
Discovery 4.8.6
Springcloud F SR2
Springboot 2.0.8

**Comment by HaojunRen** [comment]
是否加了Hystrix？

**Comment by HaojunRen** [comment]
经过测试，context.addZuulRequestHeader("reqRegion", "qa");是可以工作的，参考com.nepxion.discovery.plugin.example.zuul.impl.MyZuulFilter

**Comment by HaojunRen** [comment]
该问题已经解决，应该还没转发出去，所以在ZUUL上无法获取到自己设置的Header，我提供了一个方法
ZuulStrategyContextHolder.getZuulRequestHeaders()，在ZUUL层就通过这个方法去获取，但是来POSTMAN和context.addZuulRequestHeader需要自己分开判断

**Comment by HaojunRen** [comment]
新版本4.8.6.1

**Comment by xxy1981** [comment]
谢谢，这种方式也是判断后直接从Zuul RequestContext.getCurrentContext().getZuulRequestHeaders()获取Header属性，考虑自定义路由和灰度的使用场景比较多的话，能否通过你的组件直接把Zuul的header写到常规的HttpServletRequest里，统一通过zuulStrategyContextHolder.getRequest()来获取，省去判断取值的操作，这样就更好了。

**Comment by HaojunRen** [comment]
在HttpServletRequest里面似乎没找到，设置Header的接口。Zuul自己本身也没有做这个功能，也许在网关设置reqRegion，然后再自己用，需求不多吧。reqRegion透传到服务，是Zuul的初衷吧。

Spring Cloud Gateway里，就很好的解决了这个问题。

**Comment by HaojunRen** [comment]
参考如下代码，不是最完美，但也可以接受。在灰度路由处理上，以来自外界（POSTMAN）优先级要高于Filter
        HttpServletRequest request = zuulStrategyContextHolder.getRequest();
        // 来自于外界的Header，例如，从Postman传递过来的Header
        String token = request.getHeader("token");
        if (StringUtils.isEmpty(token)) {
            // 来自于Zuul Filter的Header
            token = zuulStrategyContextHolder.getZuulRequestHeaders().get("token");
        }

**Comment by HaojunRen** [comment]
我重构了一下，提供一个通用方法zuulStrategyContextHolder.getHeader("reqRegion");
会处理好你的问题，但需要注意，如果postman上和filter上同时设置了两个不同的reqRegion的值，以postman优先。处理逻辑在discovery-plugin-strategy-starter-zuul\src\main\java\com\nepxion\discovery\plugin\strategy\zuul\filter\ZuulStrategyFilterResolver.java，你也可以改变该逻辑。灰度发布的处理方式都是以postman优先

**Comment by xxy1981** [comment]
我本地之前的验证工作是基于zuul.ribbonIsolationStrategy=SEMAPHORE 默认验证的，zuul里context.addZuulRequestHeader("reqRegion", "qa"); 值，根据你的方案在MyDiscoveryEnabledStrategy里可以正常拿到，但我真实项目里zuul.ribbonIsolationStrategy=THREAD，按你的文档要求
# 开启Zuul网关上实现Hystrix线程隔离模式做服务隔离时，必须把spring.application.strategy.hystrix.threadlocal.supported设置为true，同时要引入discovery-plugin-strategy-starter-hystrix包，否则线程切换时会发生ThreadLocal上下文对象丢失
# zuul.ribbon-isolation-strategy=thread
# zuul.ribbonIsolationStrategy=THREAD
spring.application.strategy.hystrix.threadlocal.supported=true

我引入了discovery-plugin-strategy-starter-hystrix包，spring.application.strategy.hystrix.threadlocal.supported=true，可是在MyDiscoveryEnabledStrategy却始终拿不到zuul设置的头属性了，大师请帮忙验证一下，谢谢。

Discovery 4.8.7
Springcloud F SR2
Springboot 2.0.8

**Comment by HaojunRen** [comment]
你加我微信1394997
